// Mock data for Sheba Platform

export const ministries = [
  {
    id: 1,
    name: 'Ministry of Interior',
    icon: 'Shield',
    color: '#0d2d6d',
    services: 12,
    description: 'National ID, Residency, Permits',
  },
  {
    id: 2,
    name: 'Ministry of Health',
    icon: 'Heart',
    color: '#1dbf89',
    services: 8,
    description: 'Health Insurance, Medical Records',
  },
  {
    id: 3,
    name: 'Ministry of Education',
    icon: 'Book',
    color: '#d4a574',
    services: 10,
    description: 'School Enrollment, Certificates',
  },
  {
    id: 4,
    name: 'Municipality',
    icon: 'Building',
    color: '#0d2d6d',
    services: 15,
    description: 'Permits, Services, Utilities',
  },
  {
    id: 5,
    name: 'Tax Authority',
    icon: 'FileText',
    color: '#1dbf89',
    services: 6,
    description: 'Tax Filing, Payments, Reports',
  },
  {
    id: 6,
    name: 'Justice Ministry',
    icon: 'Scale',
    color: '#d4a574',
    services: 9,
    description: 'Notarization, Legal Services',
  },
];

export const services = [
  {
    id: 1,
    name: 'Renew National ID',
    ministry: 'Ministry of Interior',
    category: 'Identity',
    status: 'active',
    duration: '5-7 days',
    fee: 'Free',
    priority: 'high',
    eligibility: 'All citizens',
    icon: 'Card',
  },
  {
    id: 2,
    name: 'Health Insurance Registration',
    ministry: 'Ministry of Health',
    category: 'Health',
    status: 'active',
    duration: '2-3 days',
    fee: '150 AED',
    priority: 'medium',
    eligibility: 'Citizens and Residents',
    icon: 'Heart',
  },
  {
    id: 3,
    name: 'Driving License Application',
    ministry: 'Municipality',
    category: 'Transportation',
    status: 'active',
    duration: '10-14 days',
    fee: '100 AED',
    priority: 'medium',
    eligibility: 'Age 18+',
    icon: 'Car',
  },
  {
    id: 4,
    name: 'Business License',
    ministry: 'Municipality',
    category: 'Business',
    status: 'active',
    duration: '7-10 days',
    fee: '500 AED',
    priority: 'high',
    eligibility: 'Business owners',
    icon: 'Store',
  },
  {
    id: 5,
    name: 'University Enrollment',
    ministry: 'Ministry of Education',
    category: 'Education',
    status: 'active',
    duration: '15-20 days',
    fee: 'Free',
    priority: 'medium',
    eligibility: 'High school graduates',
    icon: 'GraduationCap',
  },
  {
    id: 6,
    name: 'Vehicle Registration',
    ministry: 'Municipality',
    category: 'Transportation',
    status: 'active',
    duration: '3-5 days',
    fee: '250 AED',
    priority: 'medium',
    eligibility: 'Vehicle owners',
    icon: 'Truck',
  },
];

export const notifications = [
  {
    id: 1,
    title: 'ID Renewal Complete',
    message: 'Your national ID has been renewed and is ready for pickup.',
    type: 'success',
    timestamp: new Date(Date.now() - 2 * 60 * 60 * 1000),
    read: false,
    actionUrl: '/dashboard/identity',
  },
  {
    id: 2,
    title: 'Health Insurance Updated',
    message: 'Your health insurance coverage has been updated.',
    type: 'info',
    timestamp: new Date(Date.now() - 24 * 60 * 60 * 1000),
    read: false,
    actionUrl: '/dashboard/wallet',
  },
  {
    id: 3,
    title: 'Appointment Reminder',
    message: 'Your appointment is in 2 hours at the Health Ministry.',
    type: 'warning',
    timestamp: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000),
    read: true,
  },
];

export const recentServices = [
  {
    id: 1,
    name: 'Health Insurance Registration',
    status: 'completed',
    date: new Date(Date.now() - 7 * 24 * 60 * 60 * 1000),
    ministry: 'Ministry of Health',
  },
  {
    id: 2,
    name: 'Visa Application',
    status: 'in-review',
    date: new Date(Date.now() - 14 * 24 * 60 * 60 * 1000),
    ministry: 'Ministry of Interior',
    progress: 65,
  },
  {
    id: 3,
    name: 'Driving License Renewal',
    status: 'submitted',
    date: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000),
    ministry: 'Municipality',
    progress: 30,
  },
];

export const walletCards = [
  {
    id: 1,
    type: 'national_id',
    name: 'National ID',
    issuer: 'Ministry of Interior',
    cardNumber: '784-2024-1234567',
    expiryDate: '2026-12-31',
    status: 'active',
    color: '#0d2d6d',
  },
  {
    id: 2,
    type: 'driving_license',
    name: 'Driving License',
    issuer: 'Municipality',
    cardNumber: 'DL123456',
    expiryDate: '2027-06-15',
    status: 'active',
    color: '#1dbf89',
  },
  {
    id: 3,
    type: 'health_insurance',
    name: 'Health Insurance',
    issuer: 'Ministry of Health',
    cardNumber: 'HI789012',
    expiryDate: '2025-12-31',
    status: 'expiring',
    color: '#d4a574',
  },
  {
    id: 4,
    type: 'residency',
    name: 'Residency Permit',
    issuer: 'Ministry of Interior',
    cardNumber: 'RES345678',
    expiryDate: '2028-03-20',
    status: 'active',
    color: '#0d2d6d',
  },
];

export const appointments = [
  {
    id: 1,
    service: 'National ID Renewal',
    ministry: 'Ministry of Interior',
    date: new Date(Date.now() + 3 * 24 * 60 * 60 * 1000),
    time: '10:00 AM',
    location: 'Main Branch, Downtown',
    status: 'confirmed',
  },
  {
    id: 2,
    service: 'Medical Checkup',
    ministry: 'Ministry of Health',
    date: new Date(Date.now() + 7 * 24 * 60 * 60 * 1000),
    time: '2:30 PM',
    location: 'Central Hospital',
    status: 'pending',
  },
];

export const announcements = [
  {
    id: 1,
    title: 'New Digital Services Available',
    content: 'We have launched 5 new government services on the Sheba platform.',
    date: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000),
    priority: 'high',
    icon: 'Megaphone',
  },
  {
    id: 2,
    title: 'System Maintenance Notice',
    content: 'Scheduled maintenance on March 15, 2024 from 11 PM - 1 AM.',
    date: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000),
    priority: 'medium',
    icon: 'Wrench',
  },
];

export const statistics = {
  totalCitizens: '9.2M',
  activeUsers: '4.5M',
  completedServices: '23.4M',
  avgProcessingTime: '3.2 days',
};

export const trackingSteps = [
  {
    step: 1,
    title: 'Application Submitted',
    description: 'Your application has been received',
    status: 'completed',
    date: '2024-03-01',
  },
  {
    step: 2,
    title: 'Under Review',
    description: 'Ministry officials are reviewing your documents',
    status: 'current',
    date: '2024-03-02',
  },
  {
    step: 3,
    title: 'Verification',
    description: 'Additional information may be required',
    status: 'pending',
    date: null,
  },
  {
    step: 4,
    title: 'Approved',
    description: 'Your application has been approved',
    status: 'pending',
    date: null,
  },
  {
    step: 5,
    title: 'Ready for Pickup',
    description: 'Your document is ready to be collected',
    status: 'pending',
    date: null,
  },
];
